### PR TITLE
Add support for new NodeSource repository + Node 18.x

### PR DESCRIPTION
**Pull request by stissot**
# Description

The NodeSource project has launched a [new DEB & RPM unified repository under the `nodistro` codename](https://github.com/nodesource/distributions?tab=readme-ov-file#new-update-%EF%B8%8F), using a new GPG signing key. The APT repository (Debian, Ubuntu) should also not use deprecated `apt-key` anymore. Also this cookbook should at minimum support test installing NodeJS 18.x (currently supported) and drop 17.x (not supported).

## Issues Resolved

- Default install Node 18.9.1, using Node 18.x  new `nodistro` package repository
- Repo recipe: adjust to [match 18.x manual install recommended by NodeSource](https://github.com/nodesource/distributions/wiki/Repository-Manual-Installation)
- Add support for Alma Linux 9
- Drop support for Amazon Linux 2,  CentOS 7 (unsupported by NodeSource 18.x)
- Repair the broken Inspec test commands

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

## Remarks

- We should add tests with Amazon Linux 2023 (already supported by NodeSource 18.x) when Chef and Bento support it:
   - https://github.com/chef/chef/issues/13572
   - https://github.com/chef/bento/issues/1534

### CODE REVIEW

**Comment by damacus** [comment]
If you can copy the kitchen dokken from java (if it isn't already) that'd be great.

**Comment by PowerKiKi** [comment]
> If you can copy the kitchen dokken from java (if it isn't already) that'd be great.

Isn't this supposed to be handled automatically, via @kitchen-porter, like [the last time](https://github.com/sous-chefs/nodejs/pull/263) ?

**Comment by damacus** [comment]
Thank you. I've taken this work and credited you on #283

**Comment by stissot** [comment]
You're welcome, thanks for your review and merge

**Pull request closed without merging**
