### PR TITLE
Compensate for NPM CLI deprecating -global

### LINKED ISSUE #245: NPM CLI is deprecating -global
### :speaking_head: Foreword

Debated on this being "Feature request" or "Bug"

NPM has been talking about deprecating `-global` - this cookbook needs to account for that.

## 😦  Problem Statement

Recent releases of NPM CLI have fulfilled the deprecation - causing helper to fail since it prints the deprecation warning to stderr https://github.com/sous-chefs/nodejs/blob/main/libraries/nodejs_helper.rb#L25

Luckily NPM has reverted it, but not before some damage done : https://github.com/npm/cli/releases/tag/v8.12.1

## :grey_question: Possible Solution

Update helper to use `--location=global` instead

## :arrow_heading_up: Describe alternatives you've considered

Pinning to specific NPM CLI version, but that's short-sighted

## :heavy_plus_sign: Additional context

https://github.com/npm/cli/commit/8898710220a3d84b0a9ea2a6d9cf880e50b94c9e

### PR DESCRIPTION
**Pull request by Brantone**
Move to recommended --location=global param

# Description

NPM CLI is deprecating `-global` ... recently release prints it to stderr (though another release reverts it).

## Issues Resolved

#245 

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Brantone** [comment]
Bunch of errors spitting out of Dokken that at first brush not sure how they're related.

**Comment by Brantone** [comment]
Note : 
Some older versions of NPM don't yet support `--location` ... it's not yet known when that was introduced.
Mitigation would be to do a check using `npm -v` and react according.

**Comment by ramereth** [comment]
> Note : Some older versions of NPM don't yet support `--location` ... it's not yet known when that was introduced. Mitigation would be to do a check using `npm -v` and react according.

This seems to be correct based on the failures here. This needs to be addressed before merging/releasing.

**Review by damacus — DISMISSED** [review]

**Comment by damacus** [comment]
@Brantone do you think it's been long enough now that we can assume --location will be fine all of the time?

**Comment by damacus** [comment]
I've just run npm i -g please-release and haven't received the message so I'm going to close this now

**Pull request closed without merging**
